/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exchange {
  'id' : string,
  'status' : string,
  'skillId' : string,
  'createdAt' : bigint,
  'skillTitle' : string,
  'updatedAt' : bigint,
  'message' : string,
  'providerName' : string,
  'requesterName' : string,
  'providerId' : string,
  'requesterId' : string,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'userId' : string,
  'notificationType' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
  'relatedId' : string,
}
export interface PopulateSampleDataResult {
  'sampleSkills' : Array<Skill>,
  'sampleNotifications' : Array<Notification>,
  'sampleUsers' : Array<User>,
  'sampleExchanges' : Array<Exchange>,
}
export interface Skill {
  'id' : string,
  'status' : string,
  'title' : string,
  'authorId' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'authorName' : string,
  'description' : string,
  'offeredSkill' : string,
  'category' : string,
  'wantedSkill' : string,
}
export type SortOrder = { 'asc' : null } |
  { 'desc' : null };
export interface User {
  'id' : string,
  'bio' : string,
  'username' : string,
  'createdAt' : bigint,
  'role' : string,
  'email' : string,
  'offeredSkills' : Array<string>,
  'wantedSkills' : Array<string>,
  'avatarUrl' : string,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'email' : string,
  'offeredSkills' : Array<string>,
  'wantedSkills' : Array<string>,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptRequest' : ActorMethod<[string], [] | [Exchange]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNotification' : ActorMethod<
    [string, string, string, string, string],
    Notification
  >,
  'createSkill' : ActorMethod<
    [string, string, string, string, string, string, string, Array<string>],
    Skill
  >,
  'declineRequest' : ActorMethod<[string], [] | [Exchange]>,
  'deleteNotification' : ActorMethod<[string], boolean>,
  'deleteSkill' : ActorMethod<[string], boolean>,
  'deleteUser' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExchangeById' : ActorMethod<[string], [] | [Exchange]>,
  'getNotifications' : ActorMethod<[string], Array<Notification>>,
  'getSkillById' : ActorMethod<[string], [] | [Skill]>,
  'getUnreadCount' : ActorMethod<[string], bigint>,
  'getUserById' : ActorMethod<[string], [] | [User]>,
  'getUserByPrincipal' : ActorMethod<[Principal], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAll' : ActorMethod<[], Array<Exchange>>,
  'listByCategory' : ActorMethod<[string], Array<Skill>>,
  'listByUser' : ActorMethod<[string], Array<Exchange>>,
  'listSkills' : ActorMethod<[], Array<Skill>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'markAllRead' : ActorMethod<[string], bigint>,
  'markRead' : ActorMethod<[string], boolean>,
  'populateSampleData' : ActorMethod<[], PopulateSampleDataResult>,
  'promoteToAdmin' : ActorMethod<[string], boolean>,
  'registerUser' : ActorMethod<[string, string, string], User>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSkills' : ActorMethod<[string, SortOrder], Array<Skill>>,
  'sendRequest' : ActorMethod<
    [string, string, string, string, string, string, string],
    Exchange
  >,
  'setStatus' : ActorMethod<[string, string], boolean>,
  'updateProfile' : ActorMethod<
    [string, string, Array<string>, Array<string>],
    [] | [User]
  >,
  'updateSkill' : ActorMethod<
    [string, string, string, Array<string>],
    [] | [Skill]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];