/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Exchange = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'skillId' : IDL.Text,
  'createdAt' : IDL.Int,
  'skillTitle' : IDL.Text,
  'updatedAt' : IDL.Int,
  'message' : IDL.Text,
  'providerName' : IDL.Text,
  'requesterName' : IDL.Text,
  'providerId' : IDL.Text,
  'requesterId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'userId' : IDL.Text,
  'notificationType' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'relatedId' : IDL.Text,
});
export const Skill = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'authorId' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'description' : IDL.Text,
  'offeredSkill' : IDL.Text,
  'category' : IDL.Text,
  'wantedSkill' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'email' : IDL.Text,
  'offeredSkills' : IDL.Vec(IDL.Text),
  'wantedSkills' : IDL.Vec(IDL.Text),
  'avatarUrl' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'offeredSkills' : IDL.Vec(IDL.Text),
  'wantedSkills' : IDL.Vec(IDL.Text),
  'avatarUrl' : IDL.Text,
});
export const PopulateSampleDataResult = IDL.Record({
  'sampleSkills' : IDL.Vec(Skill),
  'sampleNotifications' : IDL.Vec(Notification),
  'sampleUsers' : IDL.Vec(User),
  'sampleExchanges' : IDL.Vec(Exchange),
});
export const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRequest' : IDL.Func([IDL.Text], [IDL.Opt(Exchange)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Notification],
      [],
    ),
  'createSkill' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [Skill],
      [],
    ),
  'declineRequest' : IDL.Func([IDL.Text], [IDL.Opt(Exchange)], []),
  'deleteNotification' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteSkill' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExchangeById' : IDL.Func([IDL.Text], [IDL.Opt(Exchange)], ['query']),
  'getNotifications' : IDL.Func([IDL.Text], [IDL.Vec(Notification)], ['query']),
  'getSkillById' : IDL.Func([IDL.Text], [IDL.Opt(Skill)], ['query']),
  'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserById' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserByPrincipal' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAll' : IDL.Func([], [IDL.Vec(Exchange)], []),
  'listByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Skill)], ['query']),
  'listByUser' : IDL.Func([IDL.Text], [IDL.Vec(Exchange)], ['query']),
  'listSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], []),
  'markAllRead' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'markRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'populateSampleData' : IDL.Func([], [PopulateSampleDataResult], []),
  'promoteToAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [User], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSkills' : IDL.Func([IDL.Text, SortOrder], [IDL.Vec(Skill)], ['query']),
  'sendRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Exchange],
      [],
    ),
  'setStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [IDL.Opt(User)],
      [],
    ),
  'updateSkill' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Opt(Skill)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Exchange = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'skillId' : IDL.Text,
    'createdAt' : IDL.Int,
    'skillTitle' : IDL.Text,
    'updatedAt' : IDL.Int,
    'message' : IDL.Text,
    'providerName' : IDL.Text,
    'requesterName' : IDL.Text,
    'providerId' : IDL.Text,
    'requesterId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'userId' : IDL.Text,
    'notificationType' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'relatedId' : IDL.Text,
  });
  const Skill = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'authorId' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'description' : IDL.Text,
    'offeredSkill' : IDL.Text,
    'category' : IDL.Text,
    'wantedSkill' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'email' : IDL.Text,
    'offeredSkills' : IDL.Vec(IDL.Text),
    'wantedSkills' : IDL.Vec(IDL.Text),
    'avatarUrl' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'offeredSkills' : IDL.Vec(IDL.Text),
    'wantedSkills' : IDL.Vec(IDL.Text),
    'avatarUrl' : IDL.Text,
  });
  const PopulateSampleDataResult = IDL.Record({
    'sampleSkills' : IDL.Vec(Skill),
    'sampleNotifications' : IDL.Vec(Notification),
    'sampleUsers' : IDL.Vec(User),
    'sampleExchanges' : IDL.Vec(Exchange),
  });
  const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRequest' : IDL.Func([IDL.Text], [IDL.Opt(Exchange)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Notification],
        [],
      ),
    'createSkill' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [Skill],
        [],
      ),
    'declineRequest' : IDL.Func([IDL.Text], [IDL.Opt(Exchange)], []),
    'deleteNotification' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteSkill' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExchangeById' : IDL.Func([IDL.Text], [IDL.Opt(Exchange)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getSkillById' : IDL.Func([IDL.Text], [IDL.Opt(Skill)], ['query']),
    'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserById' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(User)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAll' : IDL.Func([], [IDL.Vec(Exchange)], []),
    'listByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Skill)], ['query']),
    'listByUser' : IDL.Func([IDL.Text], [IDL.Vec(Exchange)], ['query']),
    'listSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], []),
    'markAllRead' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'markRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'populateSampleData' : IDL.Func([], [PopulateSampleDataResult], []),
    'promoteToAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [User], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSkills' : IDL.Func(
        [IDL.Text, SortOrder],
        [IDL.Vec(Skill)],
        ['query'],
      ),
    'sendRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Exchange],
        [],
      ),
    'setStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [IDL.Opt(User)],
        [],
      ),
    'updateSkill' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Opt(Skill)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };